name: Tests
on: [push]
jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - run: docker pull rust

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: backend

      - run: cargo test
        working-directory: backend
